# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/asus/Desktop/si/Sensor/Sensor.cache/wt [current_project]
set_property parent.project_path C:/Users/asus/Desktop/si/Sensor/Sensor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/asus/Desktop/si/Sensor/Sensor.srcs/sources_1/new/Sensor.v
  C:/Users/asus/Desktop/si/Sensor/Sensor.srcs/sources_1/new/Sensor_Top.v
}
synth_design -top Sensor_Top -part xc7z020clg400-1
write_checkpoint -noxdef Sensor_Top.dcp
catch { report_utilization -file Sensor_Top_utilization_synth.rpt -pb Sensor_Top_utilization_synth.pb }
